version: '3.8'

services:
  # The Database
  db:
    image: postgres:15-alpine
    container_name: dbally_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skyta:/var/lib/postgresql/data

volumes:
  postgres_data:
